services:
  app:
    build:
      target: builder
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=sqlite.db
      - UPLOADS_PATH=uploads
      - BACKUPS_PATH=backups
    ports:
      - "3000:3000"
    command: npm run dev
    read_only: false
    tmpfs: []

  caddy:
    profiles:
      - disabled